name: Build -> Push to ECR -> Terraform deploy (ECS Fargate)

# Run on pushes to main (adjust branch as required)

on:
  workflow_dispatch:

# on:
#   push:
#     branches: [ main ]

env:
  AWS_REGION: ap-south-1
  # repo name used in infra/variables.tf (default in your repo)
  ECR_REPO: my-strapi-project-vivek-git

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Get AWS account id
        id: acct
        run: |
          echo "ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)" >> $GITHUB_ENV

      - name: Ensure ECR repository exists
        run: |
          aws ecr describe-repositories --repository-names "${{ env.ECR_REPO }}" >/dev/null 2>&1 || \
            aws ecr create-repository --repository-name "${{ env.ECR_REPO }}" --region ${{ env.AWS_REGION }}

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region ${{ env.AWS_REGION }} \
            | docker login --username AWS --password-stdin ${{ env.ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com

      - name: Build Docker image
        # Use Dockerfile.prod if you have one; fallback to Dockerfile
        run: |
          TAG="$(echo $GITHUB_SHA | cut -c1-8)"
          IMAGE="${{ env.ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPO }}:${TAG}"
          # Expose the image uri and tag to subsequent steps
          echo "IMAGE_URI=$IMAGE" >> $GITHUB_ENV
          echo "IMAGE_TAG=$TAG" >> $GITHUB_ENV

          # Build using Dockerfile.prod if present
          if [ -f Dockerfile.prod ]; then
            docker build -f Dockerfile.prod -t "${IMAGE}" .
          else
            docker build -t "${IMAGE}" .
          fi

      - name: Push image to ECR
        run: |
          docker push "${IMAGE_URI}"
          # also push :latest tag if you like
          docker tag "${IMAGE_URI}" "${{ env.ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPO }}:latest" || true
          docker push "${{ env.ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPO }}:latest" || true

         # -------------------------------
      # Step 5: Register New Task Definition
      # -------------------------------
      - name: Render new ECS task definition
        run: |
          # Replace <IMAGE_URI> in taskdef template
          sed "s|<IMAGE_URI>|${IMAGE_URI}|g" infra/taskdef-template.json > new-taskdef.json

          # Register task def
          TASK_DEF_ARN=$(aws ecs register-task-definition --cli-input-json file://new-taskdef.json --query 'taskDefinition.taskDefinitionArn' --output text)
          echo "TASK_DEF_ARN=$TASK_DEF_ARN" >> $GITHUB_ENV

      # -------------------------------
      # Step 6: Trigger CodeDeploy
      # -------------------------------
      - name: Trigger Blue/Green deployment
        run: |
          # ❗ FIX 1 — no quotes around ARN (CodeDeploy expects plain ARN, not JSON string)
          sed "s|<TASK_DEF_ARN>|${TASK_DEF_ARN}|g" appspec.yml > appspec-rendered.yml

          # ❗ FIX 2 — use ECSAllAtOnce or Canary (must match deployment_group)
          aws deploy create-deployment \
            --application-name strapi-codedeploy-app-vivek \
            --deployment-group-name strapi-ecs-deployment-group-vivek \
            --deployment-config-name CodeDeployDefault.ECSAllAtOnce \
            --revision "$(jq -n --arg content "$(cat appspec-rendered.yml)" '{revisionType:"AppSpecContent", appSpecContent:{content:$content}}')"